### ISSUE TITLE
snmema character workspace isn't passed up to C interface

### ISSUE THREAD

**Issue by jefesaurus** [snopt/snopt-interface#15]
I'm just working off the trial interface, so I can't see the internals, but is this because snmema never changes the length of the character interface?  The fortran docs in e.g. https://ccom.ucsd.edu/~optimizers/static/pdfs/snopt7-6.pdf Still show it as a parameter.

**Comment by gnowzil** [comment]
Yeah.  Not in the C/C++ interface because I never (and still haven't) figured out how to properly handle character array in Fortran and C/C++.  See [snopt_wrapper.f90](https://github.com/snopt/snopt-interface/blob/master/src/snopt_wrapper.f90) for the subroutines that can be called directly in C/C++.  There's a [global dummy](https://github.com/snopt/snopt-interface/blob/master/src/snopt_wrapper.f90#L195) `cw(lencw)` with `lencw = 500` that gets passed down.  As long as `lencw` is >= 500, snmem will never complain.

**Comment by jefesaurus** [comment]
okay, thanks for the clarification
