### ISSUE TITLE
snopt_cwrap.h also interfaces with SNOPTA

### ISSUE THREAD

**Issue by hongkai-dai** [snopt/snopt-interface#20]
On top of [`snopt_cwrap.h`](https://github.com/snopt/snopt-interface/blob/master/include/snopt_cwrap.h#L11), it says it's the C interface for SNOPTB and SNOPTC, but we also have `solveA` in snopt_cwrap.h. Should we change the documentation to include SNOPTA as well?

**Comment by jwnimmer-tri** [comment]
I think the issue here is not that any function signatures are missing from the file, but rather that this comment atop the file is incomplete / misleading:
```c++
/* File: snopt_cwrap.h
 *   C interface for SNOPTB and SNOPTC.
 */
```

**Comment by gnowzil** [comment]
I understood what he said and my reply was "snoptA should be there as well".  If the issue were anything more serious, I would've addressed it earlier.

What I say afterwards is based on OPs comment about using `solveA`.  I'm just trying to point out that he should update his calls to `snopt*` rather than `solve*`.
