### ISSUE TITLE
dyld: Symbol not found: _snlog2_

### ISSUE THREAD

**Issue by TommasoPino** [snopt/snopt-interface#7]
Hello everyone! 
I have an old version of SNOPT7 (three libraries) and I'm trying to use the cpp interface. I compile correctly the library and the interpreter library. The example sntoya.cpp was built with succes, but when I tried to launch the follow error appears:
```
dyld: Symbol not found: _snlog2_
  Referenced from: /Users/user/Downloads/snopt-interface-master/lib/libsnopt7_cpp.dylib
  Expected in: flat namespace
 in /Users/user/Downloads/snopt-interface-master/lib/libsnopt7_cpp.dylib
Abort trap: 6
```
What could I do to fix this issues? 
Thanks a lots!
Tommaso

**Comment by gnowzil** [comment]
If you have an older version of SNOPT, then you'll have to change the way the examples are compiled so that they link to the three SNOPT libraries.  The C/C++ interface assumes you've got a recent SNOPT that only has one library.  I think that if you change line 40 in Makefile.in to include the 3 libs, then it should work.
